# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ABIHackathon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  	pod 'SwiftyJSON'
  use_frameworks!

  # Pods for ABIHackathon

  target 'ABIHackathonTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
